---
layout: post
---
<p><span class="error">categoryプラグインは存在しません。</span></p>
<h3>環境</h3>
<ul>
<li><a href="http://java.sun.com/j2se/">JDK</a> 1.6.0_05</li>
<li><a href="http://hadoop.apache.org/core/">Hadoop</a> 0.17.0</li>
</ul>
<h3>利用可能な構成</h3>
<h4>Namenode/Jobtracker</h4>
<ul>
<li>Intel Xeon 3.7GHz</li>
<li>Java SE 6u5 32bit</li>
</ul>
<h4>Datanode/Tasktracker</h4>
<ul>
<li>Intel Xeon 3.7GHz</li>
<li>Java SE 6u2 64bit</li>
</ul>
<h4>Datanode/Tasktracker</h4>
<ul>
<li>AMD Dual-Core Opteron 2.8GHz</li>
<li>Java SE 6u5 32bit</li>
</ul>
<h3>NGだった構成</h3>
<h4>Namenode/Jobtracker</h4>
<ul>
<li>Intel Xeon 3.7GHz</li>
<li>Java SE 6u5 32bit</li>
</ul>
<h4>Datanode/Tasktracker</h4>
<ul>
<li>Intel Xeon 3.7GHz</li>
<li>Java SE 6u2 64bit</li>
</ul>
<h4>Datanode/Tasktracker</h4>
<ul>
<li>AMD Dual-Core Opteron 2.8GHz</li>
<li>Java SE 6u6 64bit</li>
</ul>
<pre>java.net.ConnectException: Connection timed out: no further information
java.io.IOException: 確立された接続がホスト コンピュータのソウトウェアによって中止されました。
</pre>
<p>あたりが大量に出て、Datanodeがほとんど使用不能。Tasktrackerでも、</p>
<pre>java.net.NoRouteToHostException: No route to host: no further information
</pre>
<p>などが発生する。</p>
<p>どうもネットワーク周りに非互換がある様子。</p>
